### ISSUE TITLE
Lift reloaded not working

### ISSUE THREAD

**Issue by Tsoccerguy3** [kikelkik/LiftReloaded#1]
I just tried out your lift reloaded . I removed the old one and dropped in the Lift reloaded , It does not recognize any of the old lifts on our server. It mentions on boot up a noteblock api , so we got it and the NBS tracks.zip . cant find and documentation on this at all . I only know of this plugin because Croxis just updated his source saying he is no longer maintaining Lift. Could you just do some basic documentation to get this working . Can your plugin find all our Lifts created by Croxis

**Comment by kikelkik** [comment]
I just added the documentation on https://www.spigotmc.org/resources/liftreloaded.97551/ with some words to migration from croxis Lift plugin. Please check if your new LiftReloaded/config.yml matches to the old Lift/config.yml (maybe you've configured some other base blocks etc.). 
If not, could you attach some screenshots of an example lift setup that does not work + your LiftReloaded/config.yml ?

**Comment by Tsoccerguy3** [comment]
We found out why Lift Reloaded is not working on our server. The old Lift plugin had carpet as a shaft block by default . we tried adding
- '*CARPET' 
to the shaft allowed items in your config and that is not working . When the floor blocks reset upon arrival on a floor any allowed items like a torch breaks. So your section on allowed blocks is not working as intended

![2021-11-16_19 23 53](https://user-images.githubusercontent.com/22108822/142088884-17d1e2c6-8f91-448f-919b-db67fec54bc3.png)

**Comment by Tsoccerguy3** [comment]
![2021-11-16_20 02 39](https://user-images.githubusercontent.com/22108822/142090505-ef137e77-8163-49b1-a90a-2837be03a7d7.png)
![2021-11-16_20 03 14](https://user-images.githubusercontent.com/22108822/142090519-5067d1e1-3d57-4718-a4fd-1a9e677c414f.png)

tried with rails on the glass floor . on arrival they break along with anything in the shaft

**Comment by Tsoccerguy3** [comment]
Another serious issue if riding a horse in an elevator . You get kicked for Flying and your horse dies . Probably a lot more issues . You should pull this plugin from Spigot resources until the plugin is fully tested

**Comment by Tsoccerguy3** [comment]
Here is an example of croxis code referencing the carpet as allowed in the Lift shaft

rch "carpet" (7 hits in 5 files of 67 searched)
  G:\Dev\Lift\src\main\java\net\croxis\plugins\lift\BukkitElevator.java (1 hit)
	Line 192:     public void addCarpetBlock(Block block){
  G:\Dev\Lift\src\main\java\net\croxis\plugins\lift\BukkitLiftRedstoneListener.java (2 hits)
	Line 206: 					if (gb.getRelative(BlockFace.UP).getType().toString().contains("CARPET")){
	Line 207: 						bukkitElevator.addCarpetBlock(gb.getRelative(BlockFace.UP));
  G:\Dev\Lift\src\main\java\net\croxis\plugins\lift\SpongeElevator.java (1 hit)
	Line 201: 	public void addCarpetBlock(Location<World> block){
  G:\Dev\Lift\src\main\java\net\croxis\plugins\lift\SpongeElevatorManager.java (1 hit)
	Line 112: 				|| blockType.equals(BlockTypes.CARPET)
  G:\Dev\Lift\src\main\java\net\croxis\plugins\lift\SpongeLiftRedstoneListener.java (2 hits)
	Line 203:                 if (floorBlockLocation.getRelative(Direction.UP).getBlockType() == BlockTypes.CARPET){
	Line 204:                     elevator.addCarpetBlock(floorBlockLocation.getRelative(Direction.UP));

**Comment by kikelkik** [comment]
I split this into separate issues.
Just to mention: This plugin is being used on a productive minecraft server for about 8 months (test phase). Since there were no more problems for the last 6 months I decided to publish it. Obviously, more users find more bugs, so I'm very pleased that you reported some helpful bugs and that you try out this plugin just a few days after going live!
