### ISSUE TITLE
floor names aren't working

### ISSUE THREAD

**Issue by Ceddix** [kikelkik/LiftReloaded#12]
Before with the normal Lift plugin, there was the ability to put a floor name on the sign, that was displayed. This doesn't seem to work with LiftReloaded anymore. Isn't this a feature in LiftReloaded or is there any other issue?

**Comment by kikelkik** [comment]
Hi, the feature should still work for LiftReloaded. 
Place a sign underneath the button and type the floor name on the second line. 
See 
![](https://github.com/kikelkik/LiftReloaded/blob/master/docs/showcase.gif)

**Comment by Ceddix** [comment]
So the old names aren't working anymore?

**Comment by kikelkik** [comment]
for a floorname you need two signs at a floor (above and underneath the button). You mean you could also type the floorname on the upper sign and omit the lower sign?

**Comment by Ceddix** [comment]
Yes, that was the way it worked with the legacy Lift plugin.

**Comment by Ceddix** [comment]
Do you think you could implement that again?

**Comment by Ceddix** [comment]
Thank you!
