### ISSUE TITLE
not playing music in lift on Spigot 1.18.2 

### ISSUE THREAD

**Issue by Tsoccerguy3** [kikelkik/LiftReloaded#13]
It could be NoteblockAPI needs a update or Lift Reloaded , when using Spigot 1.18.2

**Comment by kikelkik** [comment]
Which version of NoteBlockApi/LiftReloaded are you using?
Any errors/warnings in log during server startup or when riding a lift?

**Comment by Tsoccerguy3** [comment]
Paper 1.18.2 is out now https://papermc.io/api/v2/projects/paper/versions/1.18.2/builds/220/downloads/paper-1.18.2-220.jar

I tried 1.6.1 and I compiled the latest code for 1.6.2 with Lift Reloaded 1.4.1

**Comment by Tsoccerguy3** [comment]
There are no errors

**Comment by Tsoccerguy3** [comment]
There is a new Spigot and Paper API for 1.18.2

**Comment by Tsoccerguy3** [comment]
I chated with author of the NoteblockAPI he says he test it with his musicplayer and it works. Reading though Spigot API 1.18.2 it mentions that location method is changed and other things

**Comment by Tsoccerguy3** [comment]
https://hub.spigotmc.org/javadocs/bukkit/

**Comment by Tsoccerguy3** [comment]
Its fixed by deleting the config.yml . I don't know why it got corrupted when i dropped in the 2.4.1 update. Closing as fixed
