### ISSUE TITLE
scroll not working

### ISSUE THREAD

**Issue by Kanorto** [kikelkik/LiftReloaded#14]
when I tried to change the destination, I just couldn't, although the setting in the config is enabled, what should I do?

**Comment by kikelkik** [comment]
Do you click with your empty hand? is your offhand also empty? Can you hear the 'click' sound when rightclicking the sign?

**Comment by Kanorto** [comment]
Hand is empty, not sound with clicking

**Comment by Kanorto** [comment]
you are help me?

**Comment by kikelkik** [comment]
I just tested scroll selection of lift-reloaded-2.4.1 again with the latest paperspigot 1.18.2-267 and with 1.18.1-216 without problems.
Could you check your `/version` and `/version LiftReloaded`? 
You can also send me your config and/or your server ip so I could check it there.

**Comment by Kanorto** [comment]
I would like to understand how scrolling in lift should be used
I just can't do it even though the settings haven't changed much

**Comment by Kanorto** [comment]
version 2.4.1

**Comment by kikelkik** [comment]
what is your /version ?
which steps do you do (lift setup: how many floors, click where, any chat feedback, any logs with debug=true configured) and what do you expect?
can you ride the lift and select floors the normal way (withour scrolling)?

**Comment by Kanorto** [comment]
HOW SCROLL FLOORS

**Comment by Kanorto** [comment]
and close this issue

**Comment by kikelkik** [comment]
right click with your empty hand on the sign above the button of a lift with at least 3 floors. the destination (3rd line) changes when you change your currently held item (minecraft default is scrolling). right click again to confirm. 

when you title this issue with „scroll not working“ you imply a bug or misbehaviour. it seems to me now, that you simply don‘t know how to use it..

**Comment by Kanorto** [comment]
> right click with your empty hand on the sign above the button of a lift with at least 3 floors. the destination (3rd line) changes when you change your currently held item (minecraft default is scrolling). right click again to confirm.

Don`t work

**Comment by Kanorto** [comment]
not changes

**Comment by Kanorto** [comment]
i click and scroll but not changes

**Comment by kikelkik** [comment]
you can send me your server ip and tell me where a Lift is located, so I can check it there

**Comment by Kanorto** [comment]
can i send private for you, my server is private project
