### ISSUE TITLE
please remove 0.1 KB from the plugin

### ISSUE THREAD

**Issue by UnknownRebell** [kikelkik/LiftReloaded#18]
![image](https://user-images.githubusercontent.com/46301150/196010905-f0f6ea83-d98e-47fa-815b-38bcea3f9aa0.png)

Do i have to say more?

**Comment by kikelkik** [comment]
Hi @UnknownRebell,
I'm afraid I cannot reduce the jar size because the code is 100% refactored and well formatted so that every single byte is absolutely mandatory :)

Greets, 
KnownAuthor
