### ISSUE TITLE
Carpets on start floor break the lift

### ISSUE THREAD

**Issue by kikelkik** [kikelkik/LiftReloaded#2]
We found out why Lift Reloaded is not working on our server. The old Lift plugin had carpet as a shaft block by default . we tried adding
- '*CARPET' 
to the shaft allowed items in your config and that is not working . When the floor blocks reset upon arrival on a floor any allowed items like a torch breaks. So your section on allowed blocks is not working as intended

![2021-11-16_19 23 53](https://user-images.githubusercontent.com/22108822/142088884-17d1e2c6-8f91-448f-919b-db67fec54bc3.png)

_Originally posted by @Tsoccerguy3 in https://github.com/kikelkik/LiftReloaded/issues/1#issuecomment-970977019_

**Comment by kikelkik** [comment]
Will be fixed in 2.2.1

**Comment by Tsoccerguy3** [comment]
Problem fixed

**Comment by Tsoccerguy3** [comment]
You can close this portion
