### ISSUE TITLE
Plugin needs an update to work with Paper 1.20.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [kikelkik/LiftReloaded#22]
Time for an update to 1.20.x and beyond . Sign functionality has change in game , as clicking on signs allow you to edit edit

**Comment by Tsoccerguy3** [comment]
maybe even new uses for hanging signs and colored text and colored signs

**Comment by whytf** [comment]
Bump

**Comment by kikelkik** [comment]
Thank you, it's on my todo-list

**Comment by zefir-git** [comment]
this should probably be closed as completed

**Comment by Tsoccerguy3** [comment]
Fixed in current release
