### ISSUE TITLE
Cannot remove NOTE_BLOCK base

### ISSUE THREAD

**Issue by zefir-git** [kikelkik/LiftReloaded#26]
Due to using:
https://github.com/kikelkik/LiftReloaded/blob/9c2aea2fc60248469d49af57f7c444ca13b5c537/src/main/java/com/minecraftcorp/lift/bukkit/LiftPlugin.java#L47
You force-write any missing config keys from `resources/config.yml`. This makes it impossible to remove default bases like IRON_BLOCK or NOTE_BLOCK.

**Comment by kikelkik** [comment]
I'll check it

**Comment by zefir-git** [comment]
This config:

```yaml
baseBlocks:
  GOLD_BLOCK:
    speed: 0.5
```

will automatically add `NOTE_BLOCK` and `IRON_BLOCK` to the config on reboot or plugin config reload

**Comment by kikelkik** [comment]
Thanks for your note! 
I decided to go the PITA way, because I'd like to provide a default configuration where no manual changes (uncomment some lines) need to be done in order to see the plugins basic functions work.
This will be included with the next release (I want to wait for PR #29 )
