### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by Mira-LeafTown** [kikelkik/LiftReloaded#27]
Will this plugin work on Folia server in the future?

**Comment by kikelkik** [comment]
I don't know anything about Folia. Did you test it on a Folia server? Then you could tell me if it works

**Comment by Mira-LeafTown** [comment]
> I don't know anything about Folia. Did you test it on a Folia server? Then you could tell me if it works

Folia is a fork of Paper that adds regionalized multithreading capabilities to dedicated servers. The project repository is https://github.com/PaperMC/Folia
Generally, plugins have to have the "folia-supported: true" flag in their plugin.yml file to run on the Folia server. But I used some method (Dirty folia) to get it running on Folia, then when I use the elevator button I get the following error:
![IMG_20230828_081107](https://github.com/kikelkik/LiftReloaded/assets/87133530/94e26447-4310-4a07-a991-ee79a56c059f)
Folia has made some changes to the API. These changes can be seen in the project repository and in the documentation.
Folia is currently in a development state, so you may need to start a new branch if you want to provide support for the Folia server.

**Comment by jkruke** [comment]
Sorry, I currently don't want to provide support for the Folia server.
But feel free to write a PR with suggested changes for Folia-support.

**Comment by kikelkik** [comment]
Sorry, I currently don't want to provide support for the Folia server.
But feel free to write a PR with suggested changes for Folia-support.
