### ISSUE TITLE
Rails and carpets on glass floors break when the lift starts

### ISSUE THREAD

**Issue by kikelkik** [kikelkik/LiftReloaded#3]
![2021-11-16_20 02 39](https://user-images.githubusercontent.com/22108822/142090505-ef137e77-8163-49b1-a90a-2837be03a7d7.png)
![2021-11-16_20 03 14](https://user-images.githubusercontent.com/22108822/142090519-5067d1e1-3d57-4718-a4fd-1a9e677c414f.png)

tried with rails on the glass floor . on arrival they break along with anything in the shaft

_Originally posted by @Tsoccerguy3 in https://github.com/kikelkik/LiftReloaded/issues/1#issuecomment-971000853_

**Comment by kikelkik** [comment]
Will be fixed in 2.2.1

**Comment by Tsoccerguy3** [comment]
I just compiled your latest fixes and the carpet partially stays on the glass

![2021-11-16_20 27 47](https://user-images.githubusercontent.com/22108822/142199397-8c34f9ec-e23a-4018-8fed-736c90cc4543.png)

**Comment by Tsoccerguy3** [comment]
Will you add a DISCORD discussion channel

**Comment by Tsoccerguy3** [comment]
![2021-11-17_07 37 27](https://user-images.githubusercontent.com/22108822/142202094-5802a122-44ad-4e15-85e6-ad5ea36c8c83.png)
![2021-11-17_07 37 50](https://user-images.githubusercontent.com/22108822/142202110-6559a252-0d5e-461e-8431-318b48ab0d88.png)

**Comment by Tsoccerguy3** [comment]
Just in case an elevator is outside . When snow accumulates to a full block , the lift does not work

**Comment by kikelkik** [comment]
Alright thank you!
I forgot that the placement order has to be from bottom to top when restoring the glass/carpet blocks. Before, its placement has been non-deterministic which is no longer an option. 

Fixed that too.

**Comment by kikelkik** [comment]
> 
> 
> Just in case an elevator is outside . When snow accumulates to a full block , the lift does not work

In this case, the snow shouldn't be a "SNOW"-block anymore but now a "SNOW_BLOCK"-block. You add it to `floorBlocks` configuration but this doesn't make any sense to me because a player could arrive half inside a snow_block then. At this point you have to be creative (building a roof or placing barrier blocks some blocks above)

**Comment by Tsoccerguy3** [comment]
tested carpet and other blocks , works now.
