### ISSUE TITLE
Question left values in config?

### ISSUE THREAD

**Issue by CloudeLecaw** [kikelkik/LiftReloaded#30]
i checked the old config.yml vs the config version 2 of the jar file.

There i found 2 settings that are not listed in the new config.

```
checkFloor: true
# redstone enabled, an elevator can also be activated via redstone input into the block attached to the button
redstone: true
```
Do these still have an effect? or are they not used and so not needed anymore?

hmmm trying to power the theblock where the button is placed with redstone seems not to work... anymore.. or was it never a part of the plugin? or a remaining thing of the old Lift plugin?

![image](https://github.com/kikelkik/LiftReloaded/assets/12080017/5c965e79-bf7c-4608-a34a-050b4cd8b1d7)

**Comment by kikelkik** [comment]
Hi, these are indeed config properties of the old Lift plugin which weren't removed during migration. 
You can refer to the default config at the plugin's spigot page or here:
https://github.com/kikelkik/LiftReloaded/blob/master/src/main/resources/config.yml
