### ISSUE TITLE
If riding a horse in an elevator, player gets kicked and the horse dies

### ISSUE THREAD

**Issue by kikelkik** [kikelkik/LiftReloaded#4]
Another serious issue if riding a horse in an elevator . You get kicked for Flying and your horse dies . Probably a lot more issues . You should pull this plugin from Spigot resources until the plugin is fully tested

_Originally posted by @Tsoccerguy3 in https://github.com/kikelkik/LiftReloaded/issues/1#issuecomment-971029580_

**Comment by kikelkik** [comment]
The only situation I could reproduce so far:
1. ride a horse
2. place a glass block over yourself so you get stuck inside the lift
3. after the configured `secondsUntilTimeout`, you get teleported to destination but the horse doesn't and seems to stay in the lift

**Comment by Tsoccerguy3** [comment]
OK,  let me test the new fix on my test server . i will report back

**Comment by kikelkik** [comment]
There is currently no fix for this issue. I still want to find a way to reproduce

**Comment by Tsoccerguy3** [comment]
Going down riding on a horse was no problem . It was going up riding the horse that I got kicked off the server . When i joined again i was floating in the shaft and the horse is gone . I have another issue now. any time i join now i am stuck flying and get kicked . Even after disabling the plugin I am stuck in the air no mater where i warp to . I am in the process of figuring out whats happening

**Comment by kikelkik** [comment]
Maybe somewhere here the physics aren't reset for all relevant entities for some reason:
https://github.com/kikelkik/LiftReloaded/blob/master/src/main/java/com/minecraftcorp/lift/bukkit/service/ElevatorTask.java#L45 .

When you get kicked, does there appear a log (configure debug=true) message which says ".. quit within an elevator"? If not, the mechanism [here](https://github.com/kikelkik/LiftReloaded/blob/master/src/main/java/com/minecraftcorp/lift/bukkit/listener/PlayerListener.java#L131) and [here](https://github.com/kikelkik/LiftReloaded/blob/master/src/main/java/com/minecraftcorp/lift/bukkit/listener/PlayerListener.java#L145) might not be working well in this case.

**Comment by Tsoccerguy3** [comment]
What ever happened , I was stuck in a state of not being ablr to jump using space bar and floating up . no matter what gamemode I was in . I would walk but i was sliding like on ice . This problem remained even after reboots and removing the plugin. The only solution was to put the plugin back and ride the elevator again , this stopped the problem

**Comment by Tsoccerguy3** [comment]
[latest.zip](https://github.com/kikelkik/LiftReloaded/files/7567476/latest.zip)
![2021-11-18_21 44 31](https://user-images.githubusercontent.com/22108822/142556509-f2a699b9-939b-44e3-a455-f2f101bd78a6.png)
![2021-11-18_21 44 36](https://user-images.githubusercontent.com/22108822/142556518-aa22c469-10de-4ebe-9b41-8e2bff34ff14.png)

Here is the log , EssentialX Anticheat plugin might be the reason . I get kicked just before I reach the floor . The 2 pictures are whats below and above me when I log back in after after the kick .

**Comment by Tsoccerguy3** [comment]
I tested riding a saddled pig leading the pig into the lift with a stick and carrot. I get kicked for flying and on login im floating in the shaft and pig is gone. Tried riding a minecart in a lift and it does not go up , going down the minecart disappears at the bottom and i fall through the floor , This might be a conflict with Craftbook plugin

**Comment by kikelkik** [comment]
When you got kicked, you should now no longer float after relogin. 
But I'm still not sure, which of your plugins is responsible for getting kicked:
`[21:43:57] [Server thread/WARN]: MajorPayne181 was kicked for floating a vehicle too long!`

That minecart only goes up if it's not being hold by a rail. This is solved by temporary removing the rail block underneath the minecart.

**Comment by Tsoccerguy3** [comment]
the kick could be https://github.com/EssentialsX/Essentials
https://github.com/LuckPerms/LuckPerms/wiki/Command-Usage:-General

**Comment by Tsoccerguy3** [comment]
I compiled the latest code fixes and fried riding a pig lead by stick and carrot , that does work in the lift . Riding in a minecart in a lift works , but not compatible with Craftbooks minecart module . Riding a horse up in the lift still kicks a player .

**Comment by kikelkik** [comment]
I think it's neither EssentialsX (i searched in source code for "floating" => zero matches) nor LuckPerms (it's just a permission manager).
Do you also get kicked if you do the same test with the same environment with the other Lift plugin from croxis?
Could you send me a complete list of your plugins?

**Comment by Tsoccerguy3** [comment]
no kick while riding a horse in lift with croxis build 72 plugin .

lift-reloaded-2.2.1 , No kick , Horse stays hovering in shaft  stuck as in picture . Rider arrives at next floor , as in picture

![2021-11-22_14 56 20](https://user-images.githubusercontent.com/22108822/142927214-4298a57c-607c-4ff7-896c-850fc17a4d44.png)
![2021-11-22_14 57 08](https://user-images.githubusercontent.com/22108822/142927219-73a139f5-2dec-47c1-bd92-f13692ca8cf8.png)
![2021-11-22_14 57 48](https://user-images.githubusercontent.com/22108822/142927221-974434a7-8dfe-4f92-b8d5-506ccaf2c378.png)

**Comment by Tsoccerguy3** [comment]
[List_Files.txt](https://github.com/kikelkik/LiftReloaded/files/7584053/List_Files.txt)

**Comment by Tsoccerguy3** [comment]
I tested it again on a horse and got just uder the 2nd floor and the server Kicked me off.
This Time i logged in on the 1.18 Pre 6 client . Viaversion 1.18 pre 6 . Testing if 1.18 would make a difference .

**Comment by kikelkik** [comment]
You mean you always tested with MC 1.18? 
I never ran 1.18 yet

**Comment by Tsoccerguy3** [comment]
Our server has viaversion Dev. so people can log on with the 1.18 client . I tested 1.17.1 normal client and 1.18 rc4 slightly different results . I will know more tomorrow when i run viaversion 1.18 final on the 1.17.1 Paper server and when Paper 1.18 is running without viaversion .  If you want to test this out our server info is on PMC https://www.planetminecraft.com/server/sanacraft/ . /warp project  . There is a lift on the right in a tower near the road.

**Comment by Tsoccerguy3** [comment]
I compiled Paper 1.18 RC3 experimental , It is very close to what the final will be . Lift reloaded is not compatible. Lift 72 is working

**Comment by Tsoccerguy3** [comment]
Tested , lift-reloaded-2.2.2-SNAPSHOT . No errors yet . just get kicked for flying . Your welcome to join the server and do some testing of your own .

[15:56:27 WARN]: Horse (vehicle of MajorPayne181) moved wrongly! 0.285196069804897
[15:56:27 WARN]: Horse (vehicle of MajorPayne181) moved wrongly! 0.7498995259024923
[15:56:27 WARN]: Horse (vehicle of MajorPayne181) moved wrongly! 1.2146255530358303

**Comment by Tsoccerguy3** [comment]
Tried again with the horse . I get kicked and when I logon after the kick I'm in the shaft . 


![2021-12-17_10 12 32](https://user-images.githubusercontent.com/22108822/146566248-2ce265da-4406-4c00-8f9c-a15f68e8c318.png)
![2021-12-17_10 12 39](https://user-images.githubusercontent.com/22108822/146566252-4a44b7d3-e355-4963-a450-198ff8d978bd.png)



[16:11:58 WARN]: MajorPayne181 was kicked for floating a vehicle too long!
[16:11:58 INFO]: MajorPayne181 lost connection: Flying is not enabled on this server
[16:11:58 INFO]: Attempt to teleport removed player MajorPayne181 restricted
[16:11:58 INFO]: [Commodore]MajorPayne181 left the game
[16:12:07 INFO]: UUID of player MajorPayne181 is c7da63ac-b526-439d-bf27-714aee0cd638
[16:12:07 INFO]: MajorPayne181 joined the game

**Comment by Tsoccerguy3** [comment]
may be this is a difference between Lift72 and Liftreloaded 

Croxial 
=== FAQ ===
Q: Will you add build permissions?

A: No because it is not possible. Permissions are attached to players. Lifts are made from block arrangements.

**Comment by Tsoccerguy3** [comment]
I'm closing this as fixed and a permission issue

**Comment by kikelkik** [comment]
For fellow readers: how did you solve the permission issue?
