### ISSUE TITLE
compile fails , dependencies not found

### ISSUE THREAD

**Issue by Tsoccerguy3** [kikelkik/LiftReloaded#5]
compile fails 

Downloading from jitpack.io: https://jitpack.io/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.pom
Downloading from central: https://repo.maven.apache.org/maven2/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.111 s
[INFO] Finished at: 2021-11-17T04:23:52-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lift-reloaded: Could not resolve dependencies for project com.minecraftcorp:lift-reloaded:jar:2.2.1-SNAPSHOT: Failed to collect dependencies at fr.neatmonster:nocheatplus:jar:3.16.0-RC: Failed to read artifact descriptor for fr.neatmonster:nocheatplus:jar:3.16.0-RC: Could not transfer artifact fr.neatmonster:nocheatplus:pom:3.16.0-RC from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [md5-repo (http://repo.md-5.net/content/repositories/releases/, default, releases+snapshots)] -> [Help 1]

**Comment by kikelkik** [comment]
Hm, works for me.
Could you try replacing the url [here](https://github.com/kikelkik/LiftReloaded/blob/master/pom.xml#L90) with https://repo.md-5.net/repository/releases/ ?

**Comment by Tsoccerguy3** [comment]
Got futher in the compile , but fails

G:\Dev\LiftReloaded>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.minecraftcorp:lift-reloaded >-------------------
[INFO] Building LiftReloaded 2.2.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from md5-repo: https://repo.md-5.net/repository/releases/org/spigotmc/spigot-api/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
Downloading from md5-repo: https://repo.md-5.net/repository/releases/com/github/koca2000/NoteBlockAPI/-SNAPSHOT/maven-metadata.xml
Downloading from md5-repo: https://repo.md-5.net/repository/releases/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.pom
Downloaded from md5-repo: https://repo.md-5.net/repository/releases/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.pom (2.3 kB at 17 kB/s)
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/1.17.1-R0.1-SNAPSHOT/spigot-api-1.17.1-R0.1-20211116.043434-99.jar
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/net/md-5/bungeecord-chat/1.16-R0.4/bungeecord-chat-1.16-R0.4.jar
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.jar
Downloaded from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/1.17.1-R0.1-SNAPSHOT/spigot-api-1.17.1-R0.1-20211116.043434-99.jar (1.4 MB at 1.9 MB/s)
Downloading from md5-repo: https://repo.md-5.net/repository/releases/net/md-5/bungeecord-chat/1.16-R0.4/bungeecord-chat-1.16-R0.4.jar
Downloading from md5-repo: https://repo.md-5.net/repository/releases/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar
Downloading from md5-repo: https://repo.md-5.net/repository/releases/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.jar
Downloaded from md5-repo: https://repo.md-5.net/repository/releases/fr/neatmonster/nocheatplus/3.16.0-RC/nocheatplus-3.16.0-RC.jar (1.5 MB at 2.7 MB/s)
Downloading from jitpack.io: https://jitpack.io/net/md-5/bungeecord-chat/1.16-R0.4/bungeecord-chat-1.16-R0.4.jar
Downloading from jitpack.io: https://jitpack.io/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar
Downloading from jitpack.io: https://jitpack.io/com/github/koca2000/NoteBlockAPI/-57d987b541-1/NoteBlockAPI--57d987b541-1.jar
Downloaded from jitpack.io: https://jitpack.io/com/github/koca2000/NoteBlockAPI/-57d987b541-1/NoteBlockAPI--57d987b541-1.jar (135 kB at 194 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/net/md-5/bungeecord-chat/1.16-R0.4/bungeecord-chat-1.16-R0.4.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar
Downloaded from central: https://repo.maven.apache.org/maven2/net/md-5/bungeecord-chat/1.16-R0.4/bungeecord-chat-1.16-R0.4.jar (149 kB at 642 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar (327 kB at 1.3 MB/s)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lift-reloaded ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lift-reloaded ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources to .
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ lift-reloaded ---
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/0.9.10/plexus-java-0.9.10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/0.9.10/plexus-java-0.9.10.pom (5.1 kB at 95 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-languages/0.9.10/plexus-languages-0.9.10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-languages/0.9.10/plexus-languages-0.9.10.pom (4.1 kB at 88 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.pom (2.9 kB at 77 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.pom (867 B at 18 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler/2.8.4/plexus-compiler-2.8.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler/2.8.4/plexus-compiler-2.8.4.pom (6.0 kB at 163 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.pom (692 B at 15 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.pom (771 B at 20 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compilers/2.8.4/plexus-compilers-2.8.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compilers/2.8.4/plexus-compilers-2.8.4.pom (1.3 kB at 25 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/0.9.10/plexus-java-0.9.10.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-java/0.9.10/plexus-java-0.9.10.jar (39 kB at 301 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.jar (111 kB at 849 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.jar (21 kB at 99 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.jar (27 kB at 125 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.jar (4.7 kB at 14 kB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 29 source files to G:\Dev\LiftReloaded\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.384 s
[INFO] Finished at: 2021-11-17T04:39:22-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project lift-reloaded: Fatal error compiling: invalid target release: 16 -> [Help 1]

**Comment by kikelkik** [comment]
execute maven with java 16

**Comment by Tsoccerguy3** [comment]
current stable Java is 17.0.1 and the default Java with Minecraft 1.18 + will be Java 17+

**Comment by Tsoccerguy3** [comment]
I have the latest jdk-16.0.2 . maybe set a min and max Java version

**Comment by Tsoccerguy3** [comment]
Also I have apache-maven-3.8.2 , the current is apache-maven-3.8.3 and you are calling apache-maven-3.8.1

**Comment by kikelkik** [comment]
Right, but currently we go with Minecraft 1.17 (min required is Java 16). When it's time, I switch to Java 17. 

According to [this article](https://www.baeldung.com/maven-java-version#java9) it seems that I might use <release> instead of <source> and <target> in the mvn compiler configuration. I can then also compile the java16 project it with jdk17

**Comment by Tsoccerguy3** [comment]
Ok , i switched my Java_Home back to JDK 16.0.2 and it compiles

**Comment by kikelkik** [comment]
Latest maven-compiler-plugin is 3.8.1 : https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin
It has nothing to do with your actual maven installation version.

**Comment by Tsoccerguy3** [comment]
Problem fixed
