### ISSUE TITLE
Need detailed information on setting up playing music 

### ISSUE THREAD

**Issue by Tsoccerguy3** [kikelkik/LiftReloaded#7]
Can you add detailed information for setting up playing music while in the elevator , I had to read through the source code for NoteblockAPI and Lift reloaded just to get an idea of what was going on. The majority wont go this far . Better and Detailed documentation will help.

Points : to better enhance the ride

The music should start playing faintly at [ X ] number of blocks away from lift and volume gradually  rise to its intended max volume inside lift.

Details how to setup random song each time the lift is used

Examples will help , Videos of features applied .

**Comment by kikelkik** [comment]
It's in the explained config.yml section on the spigot plugin page. But I now hopefully illustrated it better in the Music section on the spigot plugin page.

> The music should start playing faintly at [ X ] number of blocks away from lift and volume gradually rise to its intended max volume inside lift.
I'm not sure.. the music should already fade in and out gradually. The music only plays during a ride. 

> Details how to setup random song each time the lift is used
songs (.nbs files within the music directory) are always randomly chosen.

> Examples will help , Videos of features applied .
It's on my agenda. I already produced a little GIF for lift usage but did not manage to publish it yet.. I'm not sure I'll produce a video. But you're welcome to do so ;)

**Comment by Tsoccerguy3** [comment]
does there need to be a note block mixed in with the iron base blocks?

**Comment by Tsoccerguy3** [comment]
Ok , I tested the base block music feature they all need to be Note_blocks and it works well

**Comment by kikelkik** [comment]
btw you can also configure any other block with music=true. What matters is the block you're standing on when starting the lift.
