### ISSUE TITLE
Plugin's config occasionally resets itself.

### ISSUE THREAD

**Issue by Vulpicula** [kikelkik/LiftReloaded#8]
Hiya,

I've got a list of custom blocks I use for various speeds in the plugin's config, and I've noticed that every now and again, config.yml wipes itself and returns to the default state, undoing any changes made.

Is there any way to prevent such a thing, or is this a fault with the plugin?

**Comment by kikelkik** [comment]
could you append your config.yml from the folder `plugins/LiftReloaded/config.yml` ?

**Comment by Vulpicula** [comment]
Can do. Was doing some more testing as well, seems like it'll reset its config file whenever there's an error with spacing and the like, although that still doesn't explain the times it has reset it at random.

<details>
  <summary>Config</summary>

maxLiftArea: 16
maxHeight: 256
minHeight: 0
debug: false
autoPlace: false
preventEntry: false
preventLeave: true
liftMobs: true
mouseScroll: true
secondsUntilTimeout: 2
floorBlocks:
- GLASS
- '*_STAINED_GLASS'
buttonBlocks:
- '*BUTTON'
signBlocks:
- '*WALL_SIGN'
shaftBlocks:
- LADDER
- SNOW
- TORCH
- VINE
- WATER
- '*RAIL'
- REDSTONE_WIRE
redstone: false
soundEnabled: true
soundVolume: 100
messages:
  destination: '&7Destination'
  currentFloor: '&7Current Floor'
  cantEnter: '&7Can''t enter elevator in use'
  cantLeave: '&7Can''t leave elevator in use'
  oneFloor: '&7There is only one floor.'
  unsafe: '&cIt is unsafe to leave a vehicle in a lift!'
  floorNotExists: '&cFloor does not exist. Check shaft for blockage'
  scrollSelectEnabled: '&7Scrollable floor selection enabled. Click on sign with an
    item for default mode'
  scrollSelectDisabled: '&7Scrollable floor selection disabled'
  timeout: '&7You have been teleported to destination due to timeout'
baseBlocks:
  COAL_BLOCK:
    speed: 0.1
  COPPER_BLOCK:
    speed: 0.25
  WAXED_COPPER_BLOCK:
    speed: 0.25
  LAPIS_BLOCK:
    speed: 0.33
  IRON_BLOCK:
    speed: 0.5
  GOLD_BLOCK:
    speed: 0.66
  DIAMOND_BLOCK:
    speed: 0.75
  NETHERITE_BLOCK:
    speed: 1.0
  NOTE_BLOCK:
    speed: 0.2
    music: true

</details>

**Comment by kikelkik** [comment]
I cannot see the indents quite well in your comment. Better put your yml text into a code block (3 times ` around it)

**Comment by Vulpicula** [comment]
```
maxLiftArea: 16
maxHeight: 256
minHeight: 0
debug: false
autoPlace: false
preventEntry: false
preventLeave: true
liftMobs: true
mouseScroll: true
secondsUntilTimeout: 2
floorBlocks:
- GLASS
- '*_STAINED_GLASS'
buttonBlocks:
- '*BUTTON'
signBlocks:
- '*WALL_SIGN'
shaftBlocks:
- LADDER
- SNOW
- TORCH
- VINE
- WATER
- '*RAIL'
- REDSTONE_WIRE
redstone: false
soundEnabled: true
soundVolume: 100
messages:
  destination: '&7Destination'
  currentFloor: '&7Current Floor'
  cantEnter: '&7Can''t enter elevator in use'
  cantLeave: '&7Can''t leave elevator in use'
  oneFloor: '&7There is only one floor.'
  unsafe: '&cIt is unsafe to leave a vehicle in a lift!'
  floorNotExists: '&cFloor does not exist. Check shaft for blockage'
  scrollSelectEnabled: '&7Scrollable floor selection enabled. Click on sign with an
    item for default mode'
  scrollSelectDisabled: '&7Scrollable floor selection disabled'
  timeout: '&7You have been teleported to destination due to timeout'
baseBlocks:
  COAL_BLOCK:
    speed: 0.1
  COPPER_BLOCK:
    speed: 0.25
  WAXED_COPPER_BLOCK:
    speed: 0.25
  LAPIS_BLOCK:
    speed: 0.33
  IRON_BLOCK:
    speed: 0.5
  GOLD_BLOCK:
    speed: 0.66
  DIAMOND_BLOCK:
    speed: 0.75
  NETHERITE_BLOCK:
    speed: 1.0
  NOTE_BLOCK:
    speed: 0.2
    music: true
```

Sorry for the delay, github didn't give me a message when ya responded. This is the config I'm currently using that does seem to work, although again, functional configs have reset themselves in the past with zero warning.

**Comment by kikelkik** [comment]
Hmm looks good. I'll add some logging when a config resets (with reason)

**Comment by kikelkik** [comment]
I added logging when the config is being resetted. Feel free to reopen the issue if you still have problems (still not sure under which circumstances you experienced this behavior).
