### ISSUE TITLE
[BUG] Lift is sometimes throwing a error while players are riding in a lift

### ISSUE THREAD

**Issue by Tsoccerguy3** [kikelkik/LiftReloaded#9]
Running Paper 1.18.1 build 76

sometimes players get stuck in lift and i need to restart server

[Liftreloaded log.txt](https://github.com/kikelkik/LiftReloaded/files/7719594/Liftreloaded.log.txt)

**Comment by Tsoccerguy3** [comment]
Added behavior 

After a reboot the player is floating around and can not get out of this state . Then in 30 seconds gets kicked for flying

**Comment by Tsoccerguy3** [comment]
The lift is now in a broken state , the glass floor has not been restored

**Comment by Tsoccerguy3** [comment]
I can not get back on the server. I'm automatically kicked for flying . have to disable plugin to logon . I'm stuck in a perpetual hovering and still get kicked from server. This Lift version needs to get fixed before people start using it. I have bigger problems now . I'm going to try and fix my state through the server host console

**Comment by Tsoccerguy3** [comment]
If any players get into this state , the only solution I found was to disable Liftreloaded and put back Lift72 . Enable flying in the server.properties , Logon , Break the signs in the lift that you got stuck on and break the base blocks , then rebuild the lift. Ride in the lift and your original state will be restored.

Liftreloaded probably is not able to get full permissions from these plugins

bukkit , vault , paper , luckperms

**Comment by kikelkik** [comment]
Which version of NoteBlockAPI are you using? 

The plugin still don't ofifcially supports MC 1.18 but I'll soon take a look at its behavior with 1.18

**Comment by Tsoccerguy3** [comment]
I compiled this https://github.com/koca2000/NoteBlockAPI

**Comment by Tsoccerguy3** [comment]
1.18.1 is latest on paper download

**Comment by kikelkik** [comment]
why did you compile NBAPI by yourself and don't drop in the jar from this site? https://www.spigotmc.org/resources/noteblockapi.19287/ 
LiftReloaded cannot find classes from NoteBlockAPI. Another Idea: Maybe you did not reload your dependencies before you compiled LiftReloaded.

**Comment by Tsoccerguy3** [comment]
Sorry for not clarifying .The error The error was before I tried the updated API . The new API was an attempt to see if that would help. There were reboots in between to make sure that all was in a clean boot state

**Comment by Tsoccerguy3** [comment]
here is a link to our servers plugins. it will help get the bugs out
https://onedrive.live.com/?cid=77B5E138E468EDE3&id=77B5E138E468EDE3%212710&parId=77B5E138E468EDE3%212507&o=OneUp

**Comment by kikelkik** [comment]
cannot download that zip (onedrive shows error). your server.properties, bukkit.yml, spigot.yml, paper.yml might also be interesting

I shortly started a Lift with 1.18 and hat no problems

**Comment by Tsoccerguy3** [comment]
The link above works for me . Maybe i need to leave my Onedrive running.
here is the configs
[Config files.zip](https://github.com/kikelkik/LiftReloaded/files/7734584/Config.files.zip)

This should work unless Microsoft is having server troubles
https://onedrive.live.com/?cid=77B5E138E468EDE3&id=77B5E138E468EDE3%212710&parId=77B5E138E468EDE3%212507&o=OneUp

**Comment by Tsoccerguy3** [comment]
I'm using Paper

https://papermc.io/downloads

**Comment by Tsoccerguy3** [comment]
I have done server updates today . I can test again . Are there any tests that you recommend that may help. Mobs or entities that i can throw into the lift to test it ?

**Comment by kikelkik** [comment]
I started a fresh paper 1.18 server with all of your plugin jars and still did'nt got kicked. maybe because any permission or worldguard flags aren't present. 

The only thing: your zip contains Lift-72 (by croxis) and lift-reloaded-2.2.1 (by me). You should not run both plugins the same time. 

> Are there any tests that you recommend that may help
Quite the opposite: You're experiencing the bugs, so I need to know from you how you get buggy behaviour with a reasonable certainity. I did visit your MC Server and used the lift at /warp project a few times (also with stucking at the sides on intent) without any problem.

**Comment by Tsoccerguy3** [comment]
I'm finding that a lot of the problem was older Paper versions . Now its only the riding a horse issue . If a permission issue that did not exist in Lift 72. Idk chances of someone riding a horse in to a lift is small. there are horses just out side the lift if you want to try one

**Comment by Tsoccerguy3** [comment]
I added you to the server perms as ironworker / there is lots open space at /warp storage or do /plot auto to get a plot to test build stuff. plot is creative mode other maps are survival . /gm 1 to change to creative . this should give you the tools to test.

**Comment by Tsoccerguy3** [comment]
I'm closing this as fixed

**Comment by kikelkik** [comment]
alright I'll eventhough try to test it on your server soon when I got some time for it
